# APIs

safetwitch:
  - https://stbackend.drgns.space
  - https://safetwitch-api.lunar.icu
  - https://api.safetwitch.eu.projectsegfau.lt

piped:
  - https://pipedapi.kavin.rocks
  - https://pipedapi.adminforge.de
  - https://api.piped.projectsegfau.lt

# Channels

twitch:
  - kapitanbombatv
  - pokochajszachy
  - rockalone
  - togglebit
  - zorchenhimer
youtube:
  - UCj0LLFUIn-bjKHRQ6mqCb2w # Krzysztof M. Maj
  - UCN5seY_Oy_GiJRhF06GfRlw # Sejm RP
