twitch:
  - h2p_gucio
  - jackie_codes
  - jaskol95
  - kapitanbombatv
  - ornicar2
  - pokochajszachy
  - primerjustin
  - rockalone
  - togglebit
  - zlemyslisz
  - zorchenhimer

youtube:
  - UCj0LLFUIn-bjKHRQ6mqCb2w # Krzysztof M. Maj
  - UCN5seY_Oy_GiJRhF06GfRlw # Sejm RP

piped:
  - https://pipedapi.kavin.rocks
  - https://pipedapi.adminforge.de
  - https://api.piped.projectsegfau.lt

safetwitch:
  - https://stbackend.drgns.space
  - https://safetwitch-api.lunar.icu
  - https://api.safetwitch.eu.projectsegfau.lt

chat-spacing: 1
