twitch:
  - jaskol95
  - kapitanbombatv
  - olaczka
  - pokochajszachy
  - rockalone
youtube:
  - UCj0LLFUIn-bjKHRQ6mqCb2w # Krzysztof M. Maj
  - UCLA_DiR1FfKNvjuUpBHmylQ # NASA
  - UCN5seY_Oy_GiJRhF06GfRlw # Sejm RP
