twitch:
  - h2p_gucio
  - jaskol95
  - ornicar2
  - pokochajszachy
  - szparumen
  - togglebit
  - wpatka
  - zlemyslisz

youtube:
  - UCxZGztWF3HTYTs3iQlRkWrg # Astrolife
  - UCpts-8H1DqUaGmUkFhbXMQQ # Kapitan Bomba
  - UCj0LLFUIn-bjKHRQ6mqCb2w # Krzysztof M. Maj
  - UCN5seY_Oy_GiJRhF06GfRlw # Sejm RP

piped:
  - https://pipedapi.kavin.rocks
  - https://pipedapi.adminforge.de
  - https://api.piped.projectsegfau.lt

safetwitch:
  - https://stbackend.drgns.space
  - https://safetwitch-api.lunar.icu
  - https://api.safetwitch.eu.projectsegfau.lt
