twitch:
  - rockalone
  - togglebit
  - szparumen
  - pokochajszachy

youtube:
  - "@krzysztofmmaj"
  - "@mateusz_astrolife"

piped:
  - https://pipedapi.adminforge.de
  - https://pipedapi.kavin.rocks

safetwitch:
  - https://safetwitch-api.lunar.icu
  - https://stbackend.drgns.space
