use_nerdfont = true
hide_display_names = true
library_tabs = ["albums", "playlists", "tracks"]

[theme]
background = "#282828"
primary = "#EBDBB2"
secondary = "#A89984"
title = "#689D6A"
playing = "#689D6A"
playing_selected = "#689D6A"
playing_bg = "#282828"
highlight = "#689D6A"
highlight_bg = "#3C3836"
error = "#EBDBB2"
error_bg = "#CC241D"
statusbar = "#282828"
statusbar_progress = "#689D6A"
statusbar_bg = "#689D6A"
cmdline = "#EBDBB2"
cmdline_bg = "#282828"
