theme = "gruvbox"

[editor]
rulers = [80]
auto-format = false

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
