# Python

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-q", "-"] }
language-servers = ["ruff"]

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

# Vue.js

[[language]]
name = "vue"
formatter = { command = 'prettier', args = ["--parser", "vue"] }
language-servers = ["volar"]

[language-server.volar]
command = "vue-language-server"
args = ["--stdio"]

[language-server.volar.config]
vue = { hybridMode = false }
typescript = { tsdk = "/usr/lib/node_modules/typescript/lib/" }

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/usr/lib/node_modules/@vue/language-server/"
languages = ["vue"]
